apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: 992382716502.dkr.ecr.us-east-1.amazonaws.com/to-do-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: port
          volumeMounts:
            - mountPath: /etc/todos/
              name: app-storage
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc  
